#!/bin/bash
apt-get -y update

#Create projects directory
mkdir -p /home/ubuntu/projects

#Install Chef/Knife
/home/ubuntu/projects/journalist/chef/install.sh

#Configure chef node
cd /home/ubuntu/projects/journalist/chef
tar -xvzf cookbooks-*.tar.gz
chef-client -z
knife node run_list add -z printer recipe[lein]
knife node run_list add -z printer recipe[git]

#Provision node
chef-client -z

#Set up logging
touch /var/log/paperboy/pb.log

#Create uberjar
cd /home/ubuntu/projects/journalist
lein uberjar
